"""
Gemini Embedding Pipeline for the Biesse RAG System.

Input:
    knowledge_base/processed/chunks.jsonl

Output:
    knowledge_base/processed/embeddings.jsonl

Pipeline:

    chunks.jsonl
        |
        v
    Gemini Embedding 2
        |
        v
    embeddings.jsonl
        |
        v
    ChromaDB

Design goals:
    - Gemini Embedding 2
    - 1536-dimensional vectors
    - Retrieval-optimized document formatting
    - Conservative free-tier token throttling
    - Batch processing
    - Retry handling
    - Resumable execution
    - Dimension consistency checks
    - Test mode
    - Safe reset mode
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from google import genai
from google.genai import types


# ============================================================
# CONFIGURATION
# ============================================================

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise RuntimeError(
        "GEMINI_API_KEY is not set.\n"
        "Add GEMINI_API_KEY=your_key to the .env file."
    )


# Gemini Embedding 2
EMBEDDING_MODEL = "gemini-embedding-2"

# Recommended reduced dimensionality for this POC.
# Google supports 768, 1536 and 3072.
OUTPUT_DIMENSIONALITY = 1536


# ------------------------------------------------------------
# Rate limiting
# ------------------------------------------------------------


TARGET_TOKENS_PER_MINUTE = 20_000

# Maximum estimated tokens sent in one API request.
#
# input-token constraints.
MAX_BATCH_TOKENS = 6_000

# Hard maximum number of chunks in one request.
MAX_BATCH_SIZE = 5

# Minimum delay between successful requests.
MIN_BATCH_DELAY_SECONDS = 5


# ------------------------------------------------------------
# Retry configuration
# ------------------------------------------------------------

MAX_RETRIES = 3

# For 429 errors, wait at least one minute because the
# free-tier problem is TPM-based.
RATE_LIMIT_RETRY_DELAY = 60

# Normal transient errors use exponential backoff.
INITIAL_RETRY_DELAY = 2


# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = (
    Path(__file__).resolve().parent.parent
)

PROCESSED_DIR = (
    PROJECT_ROOT
    / "knowledge_base"
    / "processed"
)

CHUNKS_FILE = (
    PROCESSED_DIR
    / "chunks.jsonl"
)

EMBEDDINGS_FILE = (
    PROCESSED_DIR
    / "embeddings.jsonl"
)


# ============================================================
# GEMINI CLIENT
# ============================================================

client = genai.Client(
    api_key=API_KEY
)


# ============================================================
# CHUNK LOADING
# ============================================================

def load_chunks() -> list[dict[str, Any]]:
    """
    Load chunks generated by chunker.py.

    Expected structure:

    {
        "text": "...",
        "metadata": {
            "source": "...",
            "start_page": 1,
            "end_page": 23,
            "section": "...",
            "word_count": 877,
            "chunk_id": 0
        }
    }
    """

    if not CHUNKS_FILE.exists():
        raise FileNotFoundError(
            f"Could not find:\n{CHUNKS_FILE}\n\n"
            "Run chunker.py first."
        )

    chunks: list[dict[str, Any]] = []

    with CHUNKS_FILE.open(
        "r",
        encoding="utf-8",
    ) as file:

        for line_number, line in enumerate(
            file,
            start=1,
        ):

            line = line.strip()

            if not line:
                continue

            try:
                chunk = json.loads(line)

            except json.JSONDecodeError as error:

                raise ValueError(
                    f"Invalid JSON on line "
                    f"{line_number} of "
                    f"{CHUNKS_FILE}"
                ) from error

            # Validate top-level structure.
            if "text" not in chunk:
                raise ValueError(
                    f"Chunk on line {line_number} "
                    "does not contain 'text'."
                )

            if "metadata" not in chunk:
                raise ValueError(
                    f"Chunk on line {line_number} "
                    "does not contain 'metadata'."
                )

            metadata = chunk["metadata"]

            if "chunk_id" not in metadata:
                raise ValueError(
                    f"Chunk on line {line_number} "
                    "does not contain "
                    "'metadata.chunk_id'."
                )

            chunks.append(chunk)

    return chunks


# ============================================================
# EXISTING EMBEDDINGS
# ============================================================

def load_existing_embeddings() -> dict[str, dict[str, Any]]:
    """
    Load already generated embeddings.

    Returns:

        {
            "0": {...},
            "1": {...},
            ...
        }
    """

    existing: dict[str, dict[str, Any]] = {}

    if not EMBEDDINGS_FILE.exists():
        return existing

    with EMBEDDINGS_FILE.open(
        "r",
        encoding="utf-8",
    ) as file:

        for line_number, line in enumerate(
            file,
            start=1,
        ):

            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)

            except json.JSONDecodeError:

                print(
                    f"Warning: skipping invalid JSON "
                    f"on embeddings.jsonl line "
                    f"{line_number}"
                )

                continue

            chunk_id = record.get(
                "chunk_id"
            )

            if chunk_id is None:
                continue

            existing[
                str(chunk_id)
            ] = record

    return existing


# ============================================================
# EMBEDDING VALIDATION
# ============================================================

def validate_existing_dimensions(
    existing: dict[str, dict[str, Any]]
) -> None:
    """
    All existing embeddings should have the
    dimensionality that is currently expected.

    This prevents mixing 3072-dimensional and
    1536-dimensional vectors.
    """

    if not existing:
        return

    dimensions_found: set[int] = set()

    for record in existing.values():

        embedding = record.get(
            "embedding"
        )

        if not embedding:
            continue

        dimensions_found.add(
            len(embedding)
        )

    if not dimensions_found:
        return

    if dimensions_found != {
        OUTPUT_DIMENSIONALITY
    }:

        raise RuntimeError(
            "\nExisting embeddings have "
            f"dimensions: {sorted(dimensions_found)}\n"
            f"But this pipeline is configured for "
            f"{OUTPUT_DIMENSIONALITY} dimensions.\n\n"
            "Do NOT mix embedding dimensions.\n"
            "Use:\n\n"
            "    python rag\\embeddings.py --reset\n\n"
            "to back up the old embeddings and "
            "regenerate them consistently."
        )


# ============================================================
# SAVE EMBEDDINGS
# ============================================================

def append_embeddings(
    records: list[dict[str, Any]]
) -> None:
    """
    Append generated records to embeddings.jsonl.
    """

    PROCESSED_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    with EMBEDDINGS_FILE.open(
        "a",
        encoding="utf-8",
    ) as file:

        for record in records:

            file.write(
                json.dumps(
                    record,
                    ensure_ascii=False,
                )
                + "\n"
            )


# ============================================================
# RESET EXISTING EMBEDDINGS
# ============================================================

def reset_embeddings() -> None:
    """
    Back up the current embeddings.jsonl and start fresh.

    This is necessary when changing embedding dimensions.
    """

    if not EMBEDDINGS_FILE.exists():

        print(
            "No existing embeddings.jsonl found."
        )

        return

    timestamp = (
        datetime.now()
        .strftime(
            "%Y%m%d_%H%M%S"
        )
    )

    backup_file = (
        PROCESSED_DIR
        / f"embeddings_backup_{timestamp}.jsonl"
    )

    shutil.move(
        EMBEDDINGS_FILE,
        backup_file,
    )

    print()
    print(
        "Existing embeddings backed up to:"
    )

    print(
        backup_file
    )

    print()


# ============================================================
# TEXT NORMALIZATION
# ============================================================

def normalize_text(
    text: str
) -> str:
    """
    Normalize whitespace while preserving
    the actual document content.
    """

    return " ".join(
        text.split()
    )


# ============================================================
# RETRIEVAL DOCUMENT FORMAT
# ============================================================

def prepare_document(
    chunk: dict[str, Any]
) -> str:
    """
    Prepare a chunk for Gemini Embedding 2
    retrieval embedding.

    Google recommends the structure:

        title: {title} | text: {content}

    We use the document section as the title.
    """

    metadata = chunk[
        "metadata"
    ]

    section = (
        metadata.get("section")
        or "none"
    )

    text = normalize_text(
        chunk["text"]
    )

    return (
        f"title: {section} | "
        f"text: {text}"
    )


# ============================================================
# TOKEN ESTIMATION
# ============================================================

def estimate_tokens(
    text: str
) -> int:
    """
    Approximate token count.

    This is intentionally conservative.

    For English technical text, a rough
    chars/4 estimate is useful for rate
    limiting. We add a small safety margin.
    """

    normalized = normalize_text(
        text
    )

    if not normalized:
        return 0

    estimated = max(
        1,
        len(normalized) // 4,
    )

    # 10% safety margin.
    return int(
        estimated * 1.10
    )


def estimate_chunk_tokens(
    chunk: dict[str, Any]
) -> int:
    """
    Estimate the tokens that will be sent
    to Gemini for one chunk.
    """

    prepared = prepare_document(
        chunk
    )

    return estimate_tokens(
        prepared
    )


# ============================================================
# BUILD RATE-LIMITED BATCHES
# ============================================================

def build_batches(
    chunks: list[dict[str, Any]]
) -> list[list[dict[str, Any]]]:
    """
    Build batches using both:

        - maximum chunks
        - estimated token budget

    This prevents large requests from blowing
    through the free-tier TPM limit.
    """

    batches: list[
        list[dict[str, Any]]
    ] = []

    current_batch: list[
        dict[str, Any]
    ] = []

    current_tokens = 0

    for chunk in chunks:

        chunk_tokens = (
            estimate_chunk_tokens(
                chunk
            )
        )

        # If a single chunk exceeds our target,
        # send it individually.
        if chunk_tokens > MAX_BATCH_TOKENS:

            if current_batch:

                batches.append(
                    current_batch
                )

                current_batch = []
                current_tokens = 0

            batches.append(
                [chunk]
            )

            continue

        would_exceed_tokens = (
            current_tokens
            + chunk_tokens
            > MAX_BATCH_TOKENS
        )

        would_exceed_size = (
            len(current_batch)
            >= MAX_BATCH_SIZE
        )

        if (
            current_batch
            and (
                would_exceed_tokens
                or would_exceed_size
            )
        ):

            batches.append(
                current_batch
            )

            current_batch = []
            current_tokens = 0

        current_batch.append(
            chunk
        )

        current_tokens += (
            chunk_tokens
        )

    if current_batch:

        batches.append(
            current_batch
        )

    return batches


# ============================================================
# GEMINI EMBEDDING REQUEST
# ============================================================

def generate_batch_embeddings(
    chunks: list[dict[str, Any]]
) -> list[list[float]]:
    """
    Generate one embedding for each chunk.

    Gemini Embedding 2 returns separate embeddings
    when each input is wrapped in its own Content object.
    """

    if not chunks:
        return []

    contents = []

    for chunk in chunks:

        text = prepare_document(
            chunk
        )

        contents.append(
            types.Content(
                parts=[
                    types.Part.from_text(
                        text=text
                    )
                ]
            )
        )

    for attempt in range(
        MAX_RETRIES
    ):

        try:

            response = (
                client.models.embed_content(
                    model=EMBEDDING_MODEL,
                    contents=contents,
                    config=types.EmbedContentConfig(
                        output_dimensionality=(
                            OUTPUT_DIMENSIONALITY
                        )
                    ),
                )
            )

            embeddings = [
                embedding.values
                for embedding
                in response.embeddings
            ]

            if len(embeddings) != len(
                chunks
            ):

                raise RuntimeError(
                    f"Expected "
                    f"{len(chunks)} embeddings, "
                    f"received "
                    f"{len(embeddings)}."
                )

            # Verify dimensions immediately.
            for index, embedding in enumerate(
                embeddings
            ):

                if len(embedding) != (
                    OUTPUT_DIMENSIONALITY
                ):

                    raise RuntimeError(
                        f"Chunk index {index} "
                        f"returned "
                        f"{len(embedding)} "
                        "dimensions instead of "
                        f"{OUTPUT_DIMENSIONALITY}."
                    )

            return embeddings

        except Exception as error:

            error_text = str(
                error
            )

            is_rate_limit = (
                "429" in error_text
                or "RESOURCE_EXHAUSTED"
                in error_text
            )

            if is_rate_limit:

                if attempt >= (
                    MAX_RETRIES - 1
                ):

                    raise RuntimeError(
                        "Gemini rate limit "
                        "persisted after "
                        f"{MAX_RETRIES} attempts.\n\n"
                        "The free-tier TPM limit "
                        "may still be exhausted. "
                        "Wait and rerun the "
                        "pipeline; existing "
                        "embeddings will be "
                        "skipped."
                    ) from error

                print()
                print(
                    "429 RESOURCE_EXHAUSTED."
                )

                print(
                    "Waiting "
                    f"{RATE_LIMIT_RETRY_DELAY} "
                    "seconds before retry..."
                )

                time.sleep(
                    RATE_LIMIT_RETRY_DELAY
                )

                continue

            # Non-rate-limit error.
            if attempt >= (
                MAX_RETRIES - 1
            ):

                raise RuntimeError(
                    "Gemini embedding request "
                    "failed after "
                    f"{MAX_RETRIES} attempts."
                ) from error

            delay = (
                INITIAL_RETRY_DELAY
                * (
                    2 ** attempt
                )
            )

            print(
                f"Request failed: {error}"
            )

            print(
                f"Retrying in {delay} "
                "seconds..."
            )

            time.sleep(
                delay
            )

    raise RuntimeError(
        "Unexpected embedding failure."
    )


# ============================================================
# THROTTLING
# ============================================================

def calculate_batch_delay(
    estimated_tokens: int
) -> float:
    """
    Calculate how long to wait after a batch.

    Target:
        approximately 20K tokens/minute

    This keeps us comfortably below the
    observed 30K TPM free-tier limit.
    """

    if estimated_tokens <= 0:
        return MIN_BATCH_DELAY_SECONDS

    seconds_needed = (
        estimated_tokens
        / TARGET_TOKENS_PER_MINUTE
        * 60
    )

    return max(
        MIN_BATCH_DELAY_SECONDS,
        seconds_needed,
    )


# ============================================================
# TEST MODE
# ============================================================

def test_embeddings(
    chunks: list[dict[str, Any]]
) -> None:
    """
    Test the first two chunks.
    """

    test_chunks = chunks[:2]

    if not test_chunks:

        raise RuntimeError(
            "No chunks available."
        )

    print()
    print("=" * 70)
    print("GEMINI EMBEDDING TEST")
    print("=" * 70)

    print(
        f"Model: {EMBEDDING_MODEL}"
    )

    print(
        f"Dimensions: "
        f"{OUTPUT_DIMENSIONALITY}"
    )

    print(
        f"Chunks: "
        f"{len(test_chunks)}"
    )

    print()

    for chunk in test_chunks:

        metadata = chunk[
            "metadata"
        ]

        print(
            f"Chunk ID: "
            f"{metadata['chunk_id']}"
        )

        print(
            f"Source: "
            f"{metadata.get('source')}"
        )

        print(
            f"Pages: "
            f"{metadata.get('start_page')}-"
            f"{metadata.get('end_page')}"
        )

        print(
            f"Estimated tokens: "
            f"{estimate_chunk_tokens(chunk)}"
        )

        print()

    embeddings = (
        generate_batch_embeddings(
            test_chunks
        )
    )

    print(
        "Embedding results:"
    )

    for chunk, embedding in zip(
        test_chunks,
        embeddings,
    ):

        metadata = chunk[
            "metadata"
        ]

        print()

        print(
            f"Chunk ID: "
            f"{metadata['chunk_id']}"
        )

        print(
            f"Dimensions: "
            f"{len(embedding)}"
        )

        print(
            f"First 5 values: "
            f"{embedding[:5]}"
        )

    print()

    print("=" * 70)
    print("EMBEDDING TEST PASSED")
    print("=" * 70)


# ============================================================
# FULL PIPELINE
# ============================================================

def generate_embeddings(
    chunks: list[dict[str, Any]]
) -> None:
    """
    Generate embeddings for all pending chunks.
    """

    existing = (
        load_existing_embeddings()
    )

    validate_existing_dimensions(
        existing
    )

    pending: list[
        dict[str, Any]
    ] = []

    for chunk in chunks:

        chunk_id = str(
            chunk["metadata"][
                "chunk_id"
            ]
        )

        if chunk_id not in existing:

            pending.append(
                chunk
            )

    print()
    print("=" * 70)
    print("GEMINI EMBEDDING PIPELINE")
    print("=" * 70)

    print(
        f"Model:              "
        f"{EMBEDDING_MODEL}"
    )

    print(
        f"Dimensions:         "
        f"{OUTPUT_DIMENSIONALITY}"
    )

    print(
        f"Total chunks:       "
        f"{len(chunks)}"
    )

    print(
        f"Already embedded:   "
        f"{len(existing)}"
    )

    print(
        f"Remaining:          "
        f"{len(pending)}"
    )

    print(
        f"Max batch size:     "
        f"{MAX_BATCH_SIZE}"
    )

    print(
        f"Max batch tokens:   "
        f"{MAX_BATCH_TOKENS}"
    )

    print(
        f"Target TPM:         "
        f"{TARGET_TOKENS_PER_MINUTE}"
    )

    print()

    if not pending:

        print(
            "All chunks are already embedded."
        )

        return

    batches = build_batches(
        pending
    )

    print(
        f"Planned batches: "
        f"{len(batches)}"
    )

    print()

    for batch_number, batch in enumerate(
        batches,
        start=1,
    ):

        estimated_tokens = sum(
            estimate_chunk_tokens(
                chunk
            )
            for chunk in batch
        )

        first_id = (
            batch[0]["metadata"][
                "chunk_id"
            ]
        )

        last_id = (
            batch[-1]["metadata"][
                "chunk_id"
            ]
        )

        print(
            f"Batch "
            f"{batch_number}/"
            f"{len(batches)}"
            f" | chunks={len(batch)}"
            f" | IDs={first_id}-{last_id}"
            f" | estimated_tokens="
            f"{estimated_tokens}"
        )

        embeddings = (
            generate_batch_embeddings(
                batch
            )
        )

        records = []

        for chunk, embedding in zip(
            batch,
            embeddings,
        ):

            metadata = chunk[
                "metadata"
            ]

            record = {
                "chunk_id": metadata[
                    "chunk_id"
                ],
                "text": chunk[
                    "text"
                ],
                "embedding": embedding,
                "metadata": {
                    "source": metadata.get(
                        "source"
                    ),
                    "start_page": metadata.get(
                        "start_page"
                    ),
                    "end_page": metadata.get(
                        "end_page"
                    ),
                    "section": metadata.get(
                        "section"
                    ),
                    "word_count": metadata.get(
                        "word_count"
                    ),
                },
            }

            records.append(
                record
            )

        append_embeddings(
            records
        )

        print(
            f"  Saved "
            f"{len(records)} embeddings."
        )

        processed = sum(
            len(batch)
            for batch in batches[
                :batch_number
            ]
        )

        print(
            f"  Progress: "
            f"{processed}/"
            f"{len(pending)}"
        )

        # ----------------------------------------------------
        # Rate-limit delay
        # ----------------------------------------------------

        if batch_number < len(
            batches
        ):

            delay = (
                calculate_batch_delay(
                    estimated_tokens
                )
            )

            print(
                f"  Waiting "
                f"{delay:.1f}s "
                "to stay below "
                "the TPM limit..."
            )

            time.sleep(
                delay
            )

        print()

    final_embeddings = (
        load_existing_embeddings()
    )

    print("=" * 70)
    print("EMBEDDING PIPELINE COMPLETE")
    print("=" * 70)

    print(
        f"Total embeddings saved: "
        f"{len(final_embeddings)}"
    )

    print(
        f"Expected embeddings: "
        f"{len(chunks)}"
    )

    print(
        f"Output: "
        f"{EMBEDDINGS_FILE}"
    )

    print()

    if len(final_embeddings) == len(
        chunks
    ):

        print(
            "SUCCESS: All chunks have "
            "embeddings."
        )

    else:

        print(
            "WARNING: Embedding count "
            "does not yet match chunk count."
        )

        print(
            "You can safely rerun the "
            "pipeline to continue."
        )


# ============================================================
# INSPECTION
# ============================================================

def inspect_existing_embeddings() -> None:
    """
    Print useful information about the
    current embeddings.jsonl.
    """

    if not EMBEDDINGS_FILE.exists():

        print(
            "embeddings.jsonl does not exist."
        )

        return

    existing = (
        load_existing_embeddings()
    )

    print()
    print("=" * 70)
    print("EXISTING EMBEDDINGS")
    print("=" * 70)

    print(
        f"Unique chunk IDs: "
        f"{len(existing)}"
    )

    dimensions: set[int] = set()

    for record in existing.values():

        embedding = record.get(
            "embedding"
        )

        if embedding:

            dimensions.add(
                len(embedding)
            )

    print(
        f"Dimensions found: "
        f"{sorted(dimensions)}"
    )

    chunk_ids = list(
        existing.keys()
    )

    if chunk_ids:

        print(
            f"First chunk ID: "
            f"{chunk_ids[0]}"
        )

        print(
            f"Last chunk ID: "
            f"{chunk_ids[-1]}"
        )

    print("=" * 70)


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "Generate Gemini Embedding 2 "
            "vectors for the Biesse RAG "
            "knowledge base."
        )
    )

    parser.add_argument(
        "--test",
        action="store_true",
        help=(
            "Embed only the first two "
            "chunks."
        ),
    )

    parser.add_argument(
        "--reset",
        action="store_true",
        help=(
            "Back up existing embeddings "
            "and regenerate everything."
        ),
    )

    parser.add_argument(
        "--inspect",
        action="store_true",
        help=(
            "Inspect existing embeddings "
            "without generating anything."
        ),
    )

    args = parser.parse_args()

    # Inspection does not require chunks.
    if args.inspect:

        inspect_existing_embeddings()

        return

    chunks = load_chunks()

    print(
        f"Loaded {len(chunks)} chunks."
    )

    # Reset before loading existing embeddings.
    if args.reset:

        reset_embeddings()

    if args.test:

        test_embeddings(
            chunks
        )

    else:

        generate_embeddings(
            chunks
        )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()